/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  IItIconColors,
  IItIconName,
} from './icon/interfaces';

export namespace Components {
  interface ItIcon {
    'color': IItIconColors;
    'name': IItIconName;
    'secondaryColor': IItIconColors;
    'size'?: 'small' | 'medium' | 'large';
    'src'?: string;
  }
}

declare global {


  interface HTMLItIconElement extends Components.ItIcon, HTMLStencilElement {}
  var HTMLItIconElement: {
    prototype: HTMLItIconElement;
    new (): HTMLItIconElement;
  };
  interface HTMLElementTagNameMap {
    'it-icon': HTMLItIconElement;
  }
}

declare namespace LocalJSX {
  interface ItIcon extends JSXBase.HTMLAttributes<HTMLItIconElement> {
    'color'?: IItIconColors;
    'name'?: IItIconName;
    'secondaryColor'?: IItIconColors;
    'size'?: 'small' | 'medium' | 'large';
    'src'?: string;
  }

  interface IntrinsicElements {
    'it-icon': ItIcon;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


